postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV['APP_DATABASE_NAME'] %>
  username: <%= ENV['APP_DATABASE_USER']  %>
  password: <%= ENV['APP_DATABASE_PASSWORD']%>
  host: <%= ENV['APP_DATABASE_NAME']%>


development:
  <<: *postgres

release:
  <<: *postgres

alpha:
  <<: *postgres

test:
  <<: *postgres
