postgres: &postgres
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV['APP_DATABASE_NAME'] || Rails.application.credentials.database[:database] %>
  username: <%= ENV['APP_DATABASE_USER'] || Rails.application.credentials.database[:username] %>
  password: <%= ENV['APP_DATABASE_PASSWORD']|| Rails.application.credentials.database[:password] %>

development:
  <<: *postgres

release:
  <<: *postgres

alpha:
  <<: *postgres

test:
  <<: *postgres
  database: <%= Rails.application.credentials.database[:database] +"-test" %>

